import { Router } from "express";
import { authMiddleware } from "../middlewares/auth.middleware.js";
import { LogController } from "../controllers/log.controller.js";
// import { logger } from "../utils/logger.js";

const router = Router();

// router.get("/test", (req, res) => {
//     logger.info("Test log ishlayapti! Ushbu xabar socket orqali yetib borishi kerak.");
//     logger.error("Test xato logi hammayoq yonib ketyapti! 🔥");
//     res.json({ message: "Test loglar yuborildi!" });
// });

/**
 * @swagger
 * tags:
 *   name: Logs
 *   description: System logs management
 */

/**
 * @swagger
 * /api/logs:
 *   get:
 *     summary: Gets system logs
 *     description: Fetch real-time system logs generated by winston. Pagination and time filters are supported.
 *     tags: [Logs]
 *     parameters:
 *       - in: query
 *         name: time
 *         schema:
 *           type: string
 *         description: e.g., 1h, 6h, 24h
 *       - in: query
 *         name: level
 *         schema:
 *           type: string
 *         description: e.g., info, error, warning
 *       - in: query
 *         name: source
 *         schema:
 *           type: string
 *         description: backend or telegram-bot
 *     responses:
 *       200:
 *         description: Returns fetched logs
 */
router.get("/", authMiddleware(["superadmin", "admin"]), LogController.getAllLogs);
export default router;